# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    # Convertir el tipo de versión a número
    version_map = {
      'major' => '1',
      'minor' => '2',
      'patch' => '3'
    }
    version_type = version_map[options[:version_type]] || '3'
    
    # Ejecutar el script con el tipo de versión como argumento
    sh "echo #{version_type} | ./bump-release-numbers.sh"

    # Leer las variables de GitHub Secrets directamente
    store_file = ENV["MYAPP_UPLOAD_STORE_FILE"]
    store_password = ENV["MYAPP_UPLOAD_STORE_PASSWORD"]
    key_alias = ENV["MYAPP_UPLOAD_KEY_ALIAS"]
    key_password = ENV["MYAPP_UPLOAD_KEY_PASSWORD"]

    # Configurar la firma en Gradle usando estas variables
    gradle(
      task: "clean",
      properties: {
        "MYAPP_UPLOAD_STORE_FILE" => store_file,
        "MYAPP_UPLOAD_KEY_ALIAS" => key_alias,
        "MYAPP_UPLOAD_STORE_PASSWORD" => store_password,
        "MYAPP_UPLOAD_KEY_PASSWORD" => key_password
      }
    )
    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
        "MYAPP_UPLOAD_STORE_FILE" => store_file,
        "MYAPP_UPLOAD_KEY_ALIAS" => key_alias,
        "MYAPP_UPLOAD_STORE_PASSWORD" => store_password,
        "MYAPP_UPLOAD_KEY_PASSWORD" => key_password
      }
    )

    # Luego, subimos el bundle a Google Play
    upload_to_play_store(
      track: 'beta',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
