name: Deploy Android con Fastlane  # Nombre del workflow

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Tipo de versión a incrementar'
        required: true
        type: choice
        options:
          - '1'  # Major (X.0.0)
          - '2'  # Minor (N.X.0)
          - '3'  # Patch (N.N.X)
        default: '3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar Ruby y Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: './android'

      - name: Crear keys.json en fastlane/secrets
        run: |
          mkdir -p ./fastlane/secrets
          echo "${{ secrets.KEYS_JSON }}" > ./fastlane/secrets/keys.json

      - name: Asegurar permisos del script
        run: chmod +x ./android/fastlane/bump-release-numbers.sh

      - name: Ejecutar Fastlane Deploy
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'deploy'
          subdirectory: 'android'
          options: '{ "version_type": "${{ github.event.inputs.version_type }}" }'

      - name: Borrar keys.json (seguridad)
        if: always()
        run: rm -f ./fastlane/secrets/keys.json
