on:
  workflow_dispatch:  # Solo se ejecutará manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar Ruby y Bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          gem install bundler

      - name: Instalar dependencias del proyecto
        run: bundle install

      - name: Instalar Fastlane
        run: gem install fastlane

      - name: Crear keys.json en fastlane/secrets
        run: |
          mkdir -p ./fastlane/secrets
          echo "${{ secrets.KEYS_JSON }}" > ./fastlane/secrets/keys.json

      - name: Asegurar permisos del script
        run: chmod +x ./bump-release-numbers.sh

      - name: Ejecutar Fastlane Deploy
        run: bundle exec fastlane android deploy

      - name: Borrar keys.json (seguridad)
        if: always()
        run: rm -f ./fastlane/secrets/keys.json
# Forzar detección de workflow
