name: Deploy Android con Fastlane  # Nombre del workflow

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Tipo de versión a incrementar'
        required: true
        type: choice
        options:
          - 'major'  # X.0.0
          - 'minor'  # N.X.0
          - 'patch'  # N.N.X
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
          # cache: 'yarn'  # Deshabilitar caché temporalmente

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Verificar instalación de dependencias
        run: |
          yarn check
          bundle check

      - name: Configurar Ruby y Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: './android'

      - name: Crear keys.json en fastlane/secrets
        run: |
          mkdir -p ./fastlane/secrets
          echo "${{ secrets.KEYS_JSON }}" > ./fastlane/secrets/keys.json

      - name: Asegurar permisos del script
        run: chmod +x ./android/fastlane/bump-release-numbers.sh

      - name: Listar estructura de archivos
        run: |
          echo "Estructura de archivos:"
          ls -R

      - name: Ejecutar Fastlane Deploy
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'deploy'
          subdirectory: 'android'
          options: '{ "version_type": "${{ github.event.inputs.version_type }}" }'

      - name: Crear bundle de release (depuración)
        run: |
          cd android
          ./gradlew createBundleReleaseJsAndAssets

      - name: Borrar keys.json (seguridad)
        if: always()
        run: rm -f ./fastlane/secrets/keys.json