name: Deploy Android con Fastlane

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Tipo de versión a incrementar'
        required: true
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Azul Zulu JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'  # Usa Azul Zulu como distribución de Java

      - name: Verificar versión de Java
        run: java -version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install

      - name: Configurar Ruby y Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: './android'

      - name: Crear keys.json en fastlane/secrets
        run: |
          mkdir -p ./fastlane/secrets
          echo "${{ secrets.KEYS_JSON }}" > ./fastlane/secrets/keys.json

      - name: Asegurar permisos del script
        run: chmod +x ./android/fastlane/bump-release-numbers.sh

      - name: Ejecutar Fastlane Deploy
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'deploy'
          subdirectory: 'android'
          options: '{ "version_type": "${{ github.event.inputs.version_type }}" }'

      - name: Borrar keys.json (seguridad)
        if: always()
        run: rm -f ./fastlane/secrets/keys.json