name: Deploy Android con Fastlane  # Nombre del workflow

on:
  workflow_dispatch:  # Solo se ejecutará manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar Ruby y Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false

      - name: Instalar dependencias del proyecto
        run: |
          gem install bundler -v 2.4.22
          bundle install

      - name: Crear keys.json en fastlane/secrets
        run: |
          mkdir -p ./fastlane/secrets
          echo "${{ secrets.KEYS_JSON }}" > ./fastlane/secrets/keys.json

      - name: Asegurar permisos del script
        run: chmod +x ./android/fastlane/bump-release-numbers.sh

      - name: Ejecutar Fastlane Deploy
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'deploy'

      - name: Borrar keys.json (seguridad)
        if: always()
        run: rm -f ./fastlane/secrets/keys.json
